name: macaron-stack
type: nodejs:18
hooks:
  build: |
    cd /app/feathers-basics
    ./fastly-install.sh
    npm install
    cd /app/remix && npm install --dev
  post_deploy:
    PATH=$PATH:/app/.fastly
web:
  commands:
    start: |
      npx ts-node app.ts
disk: 512
relationships:
  pgdb: "postgresqldb:postgresql"
variables:
  env:
    FASTLY_API_TOKEN: abcdefghi
mounts:
  '.config/fastly':
    source: local
    source_path: fastly
  'remix/bin':
    source: local
    source_path: bin