- name: feathers
  type: nodejs:18
  source:
    root: feathers-basics
  hooks:
    build: |
      npm install
  web:
    commands:
      start: |
        npx ts-node app.ts
  disk: 512
  relationships:
    pgdb: "postgresqldb:postgresql"