- name: feathers
  type: nodejs:18
  source:
    root: feathers-basics
  hooks:
    build: |
      
  web:
    commands:
      start: |
        
  disk: 512
  relationships:
    pgdb: "postgresqldb:postgresql"