- name: remix
  type: nodejs:18
  source:
    root: remix
  hooks:
    build: |
      ./fastly-install.sh
      npm install
      npm run build

- name: remix2
  type: nodejs:18
  source:
    root: remix2
  hooks:
    build: |
      npm install
