- name: feathers
  type: nodejs:18
  source:
    root: feathers-basics
  hooks:
    build: |
      ./fastly-install.sh
      npm install
  web:
    commands:
      start: |
        npx ts-node app.ts
  disk: 512
  relationships:
    pgdb: "postgresqldb:postgresql"
  mounts:
    '.config/fastly':
      source: local
      source_path: fastly