- name: remix
  type: nodejs:18
  source:
    root: remix
  hooks:
    build: |
      ./fastly-install.sh
      npm install --include=dev
      npm run build
      npm run deploy
  mounts:
    '.config':
      source: tmp
      source_path: files/.config